# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('barcode', models.CommaSeparatedIntegerField(max_length=200)),
                ('created', models.DateTimeField()),
                ('currency', models.CharField(max_length=4)),
                ('discount', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('modified', models.DateTimeField()),
                ('order_id', models.PositiveIntegerField()),
                ('order_type', models.CharField(max_length=15)),
                ('quantity', models.PositiveIntegerField()),
                ('affiliate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('modified', models.DateTimeField()),
                ('privacy', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('timezone', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('tags', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('currency', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity_available', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('type', models.SmallIntegerField()),
                ('visible', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='eventbrite.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('address_2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=20)),
                ('postal_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=30)),
                ('country_code', models.CharField(max_length=5)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventbrite.Venue'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='eventbrite.Contact'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='eventbrite.Ticket'),
        ),
    ]
