# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='region',
            field=models.CharField(max_length=60),
        ),
    ]
