# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0002_auto_20161002_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=130),
        ),
    ]
