# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0004_auto_20161002_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address_2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
