# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0005_auto_20161002_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(max_length=30),
        ),
    ]
