# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0010_auto_20161003_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='barcode',
            field=models.CommaSeparatedIntegerField(max_length=400),
        ),
    ]
