# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0011_auto_20161003_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='discount',
            field=models.CharField(max_length=40),
        ),
    ]
