# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0014_auto_20161005_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='include_fee',
            field=models.CharField(default='false', max_length=60),
        ),
        migrations.AddField(
            model_name='ticket',
            name='max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 13, 10, 48, 911560, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
