# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0017_auto_20161111_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
